project: 
  type: book

book: 
  page-navigation: true
  title: "HTC/HPC for Stock Assessments" 
  site-url: "https://moshima-pifsc.github.io/NSASS-HTC-HPC-Computing-dep" 
  repo-url: "https://moshima-pifsc/NSASS-HTC-HPC-Computing-dep"
  repo-actions: [source, issue]
  search: true
  author:
    - name: Nicholas Ducharme-Barth
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
    - name: Megumi Oshima
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
  chapters:
    - index.qmd
  

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 3
